### ISSUE TITLE
ngt fails to install

### ISSUE THREAD

**Issue by gpapadis** [maumueller/ann-benchmarks-reproducibility#13]
HI!
When running the following command on Ubuntu 18.04, I get the attached [error](https://github.com/maumueller/ann-benchmarks-reproducibility/files/7562141/error.txt).
python3 install.py --proc 5 

Essentially, the installation of the ngt method fails. All previous installation steps have been successfully completed. 
How can I fix this error?

**Comment by maumueller** [comment]
Hi @gpapadis. NGT requires a AVX2-capable CPU for compilation, which does not seem to be the case on your setup. 

Could you add the output of running `cat /proc/cpuinfo  | grep flags`?

**Comment by gpapadis** [comment]
Thanks for the prompt reply! This is the output of the above command:
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm arat pln pts md_clear flush_l1d

**Comment by maumueller** [comment]
@gpapadis: This seems like an architecture that is not support by the implementation. You could see if a newer release helps by removing the commit id in <https://github.com/maumueller/ann-benchmarks-reproducibility/blob/master/install/Dockerfile.ngt#L7> (last sha-string). However, it will then not be the same version as the one that has been used in the experiments of the paper.

**Comment by gpapadis** [comment]
Thanks a lot for the clarification!
