### ISSUE TITLE
PyNNDescent slow

### ISSUE THREAD

**Issue by maumueller** [maumueller/ann-benchmarks-reproducibility#7]

**Comment by lmcinnes** [comment]
If PyNNDescent is having significant performance issues I would be happy to try to work out the problems. Did this get resolved in some way, or is it still a potential issue?

**Comment by maumueller** [comment]
Thanks for following up on this :-) 

This is an bit of an odd project becaues it reproduces runs with versions that are from Summer 2018. I installed an old pynndescent via pip and that turned out to perform at around 20 qps :-) Compiling from source works just fine.

**Comment by lmcinnes** [comment]
Okay, good to know. Thank you!
